### PR TITLE
Add Autodesk internship opening 

### PR DESCRIPTION
**Pull request by simonjulianl**
Add Autodesk tech internship

### CODE REVIEW

**Comment by sushinoya** [comment]
Hi @simonjulianl, sorry I just merged a different PR so you might have to fix the conflicts. I can do it if not. Also, why just "Licensing Entitlement Management (DPE-SPG)"? From what I see there are many positions - 

Screenshot 2021-09-11 at 9 41 36 PM

Maybe they weren't there when you made the PR since they were posted recently.

**Comment by simonjulianl** [comment]
I can fix the conflicts! I see I think its new because when I applied there was only 1 position for Software Engineer Intern for Autodesk

**Comment by sushinoya** [comment]
@simonjulianl Thanks for such a quick fix! Can we change the notes from "Software Engineering Internship" to "Multiple positions open"? Also, thanks for making the PR!

**Comment by simonjulianl** [comment]
yeah sure!

**Comment by sushinoya** [comment]
@simonjulianl Thank you! And thanks for the PR :)

**Comment by simonjulianl** [comment]
Np

**Pull request merged**
