### PR TITLE
Update Shopback link + Add other links

### PR DESCRIPTION
**Pull request by Jh123x**
Add:
(Both seems to offer a very technical role based on description)
1. Foodpanda (SWE) 
1. Seimons (SWE/ data analytics)

Update:
1. Shopback

### CODE REVIEW

**Comment by sushinoya** [comment]
Hi @Jh123x! Sorry that I only got to your PR now. Somehow it did not show up in my Github Notifications. Anyway, I have a few comments about your changes - 

1. Thanks for fixing the Shopback link! I was wondering if [this](https://jobs.lever.co/shopback-2/3c60180b-6dd1-48a6-9d0e-4edf80be1fc3) would be better since it is a direct link to their only SWE internship. Although, I think the link you provided is fine too.

2. For Vanitee and Tickled Media, the links are search results from [internsg.com](https://www.internsg.com/). Had a hard time going through quite a lot of pages of internship postings which are unrelated to tech. Perhaps a link that filters only their tech roles would have been better.

3. Also, Vanitee, Tickled Media, and The Smart Local seem to be looking more for content creators and editors instead of tech interns. I do see one or two postings for their IT departments. But I am unsure about them being tech-heavy as opposed to being tech support for their business. Unless you have a good idea of what tech interns at these places do, I am a bit hesitant to put them on this list. But of course, if you know of the work their tech interns do then we could talk about that :)

**Comment by Jh123x** [comment]
> Hi @Jh123x! Sorry that I only got to your PR now. Somehow it did not show up in my Github Notifications. Anyway, I have a few comments about your changes -
> 
> 1. Thanks for fixing the Shopback link! I was wondering if [this](https://jobs.lever.co/shopback-2/3c60180b-6dd1-48a6-9d0e-4edf80be1fc3) would be better since it is a direct link to their only SWE internship. Although, I think the link you provided is fine too.
> 2. For Vanitee and Tickled Media, the links are search results from [internsg.com](https://www.internsg.com/). Had a hard time going through quite a lot of pages of internship postings which are unrelated to tech. Perhaps a link that filters only their tech roles would have been better.
> 3. Also, Vanitee, Tickled Media, and The Smart Local seem to be looking more for content creators and editors instead of tech interns. I do see one or two postings for their IT departments. But I am unsure about them being tech-heavy as opposed to being tech support for their business. Unless you have a good idea of what tech interns at these places do, I am a bit hesitant to put them on this list. But of course, if you know of the work their tech interns do then we could talk about that :)

Thank you for the comments. Update based on the comments.
Will add them back after finding out more about their internships.

**Comment by sushinoya** [comment]
@Jh123x Thanks for updating the PR! LGTM for Shopback and foodpanda. As for Siemens, I went to their company's website and could not find the internship position on their Careers page. The link you provided is from gradsingapore and there the position was posted on 29 Jul 2019. So, I worry that it might just be an unmonitored listing that Siemens did not takedown.

**Comment by Jh123x** [comment]
> @Jh123x Thanks for updating the PR! LGTM for Shopback and foodpanda. As for Siemens, I went to their company's website and could not find the internship position on their Careers page. The link you provided is from gradsingapore and there the position was posted on 29 Jul 2019. So, I worry that it might just be an unmonitored listing that Siemens did not takedown.

I see. Read the description but didn't see the date x.x
I will amend and update the pr

**Comment by sushinoya** [comment]
@Jh123x Thank you so much! Let me know if you wanna make any other changes cause otherwise the PR looks good to me

**Review by sushinoya — APPROVED** [review]

**Comment by Jh123x** [comment]
> @Jh123x Thank you so much! Let me know if you wanna make any other changes cause otherwise the PR looks good to me

Thank you! Currently not looking to make other changes. Will make another PR if there are additional changes

**Pull request merged**
